const books = [
  {
    name: 'The Art of Programming',
    year: 2005,
    author: 'Alan Turing',
    summary: 'A comprehensive guide to programming principles and algorithms.',
    publisher: 'TechBooks Publishing',
    pageCount: 500,
    readPage: 200,
    reading: true,
  },
  {
    name: 'Galaxy Explorers',
    year: 2010,
    author: 'Samantha Johnson',
    summary: 'Join a group of young explorers on their journey through the galaxy.',
    publisher: 'Stellar Press',
    pageCount: 350,
    readPage: 150,
    reading: false,
  },
  {
    name: 'Mindfulness in Daily Life',
    year: 2018,
    author: 'Emma Smith',
    summary: 'Practical tips on incorporating mindfulness into your everyday routine.',
    publisher: 'Zenith Books',
    pageCount: 200,
    readPage: 100,
    reading: true,
  },
  {
    name: 'The Mystery of Midnight Manor',
    year: 2022,
    author: 'James Mysteryson',
    summary: 'An intriguing mystery set in a haunted mansion at midnight.',
    publisher: 'Enigma Publications',
    pageCount: 400,
    readPage: 250,
    reading: true,
  },
  {
    name: 'Cooking with Colors',
    year: 2015,
    author: 'Chef Maria Rodriguez',
    summary: 'A vibrant cookbook with recipes organized by color for a visually stunning culinary experience.',
    publisher: 'Gourmet Editions',
    pageCount: 300,
    readPage: 200,
    reading: false,
  },
];

module.exports = books;
